FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -g tsc && npm install -g concurrently 
RUN npm install 
COPY . .
RUN npm run build 
EXPOSE 3000  
CMD [ "node", "./src/app.js"]
